# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_auto_20161025_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
    ]
