# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_remove_usuario_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=350)),
                ('Remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('descricao', models.CharField(max_length=1000)),
                ('validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='servico',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='servico.Servico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.SubCategoria'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='Servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.Servico'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.Solicitacao'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='Solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.Solicitacao'),
        ),
    ]
