# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0005_avaliacao_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='imagem',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
