# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0006_auto_20161030_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
