# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0007_auto_20161030_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='Solicitacao',
            new_name='solicitacao',
        ),
        migrations.RenameField(
            model_name='mensagem',
            old_name='Remetente',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='mediaAvaliacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servico',
            name='patrocinado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servico',
            name='totalAvaliacoes',
            field=models.IntegerField(default=0),
        ),
    ]
