# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-04 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0008_auto_20161030_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacao',
            old_name='Servico',
            new_name='servico',
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='Usuario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='Data',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
