# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-04 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0010_auto_20170304_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateTimeField(),
        ),
    ]
