# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-04 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0011_auto_20170304_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_atendimento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[['cancelado', 'Cancelado'], ['pendente', 'Pendente'], ['confirmado', 'Confirmado'], ['concluido', 'Concluido'], ['avaliado', 'Avaliado']], default='pendente', max_length=10),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data_fim',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateTimeField(null=True),
        ),
    ]
