# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-03 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0014_auto_20170501_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='hora_fim',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='hora_inicio',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='minutos_fim',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='minutos_inicio',
            field=models.IntegerField(default=0),
        ),
    ]
