# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-04 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0016_auto_20170504_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='hora_atendimento',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='minutos_atendimento',
            field=models.IntegerField(default=0),
        ),
    ]
