# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-05 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0019_auto_20170504_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='servico',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='prestador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Prestador', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
