# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-10 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0020_auto_20170505_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
