# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-10 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0021_auto_20170510_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.Categoria'),
        ),
    ]
