# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-10 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0022_auto_20170510_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
