# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-30 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0023_auto_20170510_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mediaAvaliacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='totalAvaliacoes',
            field=models.IntegerField(default=0),
        ),
    ]
