# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-30 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0024_auto_20170630_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_fantasia',
            field=models.CharField(default='', max_length=30),
        ),
    ]
