# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-10 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0026_auto_20170630_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
