# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-23 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0029_solicitacao_respondida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='respondida',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(default='pendente', max_length=10),
        ),
    ]
