# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-09 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0031_orcamento_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='minutos_fim',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='minutos_inicio',
        ),
    ]
