# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0032_auto_20170909_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
