# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0034_auto_20170911_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='user',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='solicitacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servico.Solicitacao'),
            preserve_default=False,
        ),
    ]
