# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-13 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0035_auto_20170913_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='prestador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prestador', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
